apiVersion: v1
kind: Service
metadata:
  namespace: learning
  clusterName: minikube
  name: learning-s
spec:
  selector: 
    app: learning
  type: NodePort
  ports:
      - name: port-mapping1
        port: 80
        nodePort: 30001

