apiVersion: v1
kind : PersistentVolume
metadata:
  namespace: learning
  clusterName: minikube
  name: learning-v
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: "/Users/amitmohleji/learning/kubernetes1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: learning
  clusterName: minikube
  name: learning-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi