apiVersion: v1
kind: Namespace
metadata:
  name: xl-demo
---
apiVersion: v1
kind : PersistentVolume
metadata:
  namespace: xl-demo
  name: xlr
spec:
  storageClassName: xlr
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: "/home/mount/xl-licenses/"
---
apiVersion: v1
kind : PersistentVolume
metadata:
  namespace: xl-demo
  name: xld
spec:
  storageClassName: xld
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: "/home/mount/xl-licenses/"