apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: {{.Values.namespace}}
  clusterName: minikube
  name: learning-in
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
       paths:
         - backend:
            serviceName: learning-s
            servicePort: 80
           path:  /{{.Values.namespace}}
           
           