apiVersion: v1
kind: Pod
metadata:
  namespace: {{.Values.namespace}}
  clusterName: minikube
  name: learning-p
  labels:
    app: {{.Values.namespace}}
spec:
  containers:
    - name: httpd
      image: httpd:2.4
      volumeMounts:
        - name: file-volume
          mountPath: /etc/kube
  volumes:
    - name: file-volume
      persistentVolumeClaim:
        claimName: learning-pv-claim
  restartPolicy: Never

          
        
