apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.namespace}}
  clusterName: minikube
  name: learning-s
spec:
  selector: 
    app: {{.Values.namespace}}
  type: NodePort
  ports:
      - name: port-mapping1
        port: 80

