apiVersion: v1
kind : PersistentVolume
metadata:
  namespace: {{.Values.namespace}}
  clusterName: minikube
  name: {{.Values.namespace}}-v
spec:
  storageClassName: {{.Values.namespace}}
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: "/learning/{{.Values.namespace}}/kubernetes1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{.Values.namespace}}
  clusterName: minikube
  name: learning-pv-claim
spec:
  storageClassName: {{.Values.namespace}}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi